import {
  Tenant,
  Site,
  BuildingZone,
  Gate,
  Department,
  AppUser,
  VisitorProfile,
  Visit,
  BadgeTemplate,
  HardwareDevice,
  AuditEvent,
  EdgeSyncEvent,
  UATTestCase
} from '../types';

export const INITIAL_TENANTS: Tenant[] = [
  {
    id: 'ten-tata-01',
    name: 'Tata Consultancy & Advanced Systems',
    code: 'TATA',
    tier: 'ENTERPRISE_PREMIUM',
    status: 'ACTIVE',
    timezone: 'Asia/Kolkata',
    locale: 'en-IN',
    databaseRef: 'tenant_db_tata_mumbai_01',
    databaseHealth: 'HEALTHY',
    migrationVersion: '2026.09.v14',
    retentionDays: 365,
    features: {
      kioskMode: true,
      biometricVerification: false,
      whatsappNotifications: true,
      edgeOfflineEnabled: true,
      multiLevelApproval: true,
    },
    branding: {
      primaryColor: '#00539B',
      logoText: 'TATA ENTERPRISE',
    },
    whitelabelBranding: {
      enabled: true,
      companyName: 'Tata Consultancy Services',
      portalTitle: 'Tata Physical Security & Visitor Portal',
      tagline: 'Zero-Trust Campus Access & Perimeter Defense',
      primaryColor: '#00539B',
      secondaryColor: '#003366',
      headerBackground: 'DARK_NAVY',
      hidePoweredBy: false,
      fontFamily: 'Plus Jakarta Sans',
      fontStyle: 'normal',
      fontWeight: '600',
      letterSpacing: 'normal',
      textTransform: 'none',
      fontSizeBase: '14px',
      logoUrl: `data:image/svg+xml;utf8,<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 240 60"><rect width="240" height="60" rx="8" fill="%2300539B"/><text x="24" y="38" fill="%23FFFFFF" font-family="Arial, sans-serif" font-size="26" font-weight="900" letter-spacing="4">TATA</text><text x="110" y="37" fill="%2393C5FD" font-family="Arial, sans-serif" font-size="14" font-weight="700">SERVICES</text></svg>`,
      logoFileName: 'tata_consultancy_logo.svg',
      logoHeightPx: 38,
    },
    createdAt: '2025-01-15T08:00:00Z',
  },
  {
    id: 'ten-reliance-02',
    name: 'Reliance Jio Digital Infocomm',
    code: 'RJIO',
    tier: 'MISSION_CRITICAL',
    status: 'ACTIVE',
    timezone: 'Asia/Kolkata',
    locale: 'en-IN',
    databaseRef: 'tenant_db_reliance_navi_02',
    databaseHealth: 'HEALTHY',
    migrationVersion: '2026.09.v14',
    retentionDays: 730,
    features: {
      kioskMode: true,
      biometricVerification: true,
      whatsappNotifications: true,
      edgeOfflineEnabled: true,
      multiLevelApproval: true,
    },
    branding: {
      primaryColor: '#0F4C81',
      logoText: 'JIO CYBER PARK',
    },
    whitelabelBranding: {
      enabled: true,
      companyName: 'Reliance Jio Digital Infocomm',
      portalTitle: 'Reliance Global Facility Access Hub',
      tagline: 'Growth is Life • Smart Campus Security',
      primaryColor: '#0F4C81',
      secondaryColor: '#E63946',
      headerBackground: 'DARK_NAVY',
      hidePoweredBy: false,
      fontFamily: 'Inter',
      fontStyle: 'normal',
      fontWeight: '600',
      letterSpacing: 'normal',
      textTransform: 'none',
      fontSizeBase: '14px',
      logoUrl: `data:image/svg+xml;utf8,<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 240 60"><rect width="240" height="60" rx="8" fill="%230F4C81"/><circle cx="34" cy="30" r="16" fill="%23E63946"/><text x="60" y="38" fill="%23FFFFFF" font-family="Arial, sans-serif" font-size="20" font-weight="800" letter-spacing="1.5">RELIANCE</text></svg>`,
      logoFileName: 'reliance_jio_logo.svg',
      logoHeightPx: 36,
    },
    createdAt: '2025-03-20T10:30:00Z',
  },
  {
    id: 'ten-infosys-03',
    name: 'Infosys NextGen Digital Campus',
    code: 'INFY',
    tier: 'ENTERPRISE_PREMIUM',
    status: 'ACTIVE',
    timezone: 'Asia/Kolkata',
    locale: 'en-IN',
    databaseRef: 'tenant_db_infy_bengaluru_03',
    databaseHealth: 'HEALTHY',
    migrationVersion: '2026.09.v14',
    retentionDays: 365,
    features: {
      kioskMode: true,
      biometricVerification: true,
      whatsappNotifications: true,
      edgeOfflineEnabled: true,
      multiLevelApproval: true,
    },
    branding: {
      primaryColor: '#007CC3',
      logoText: 'INFOSYS TECH PARK',
    },
    whitelabelBranding: {
      enabled: true,
      companyName: 'Infosys NextGen Digital Campus',
      portalTitle: 'Infosys Visitor Identity & Smart Gates',
      tagline: 'Navigate your next • Smart Campus Gatekeeper',
      primaryColor: '#007CC3',
      secondaryColor: '#1A365D',
      headerBackground: 'DARK_NAVY',
      hidePoweredBy: false,
      fontFamily: 'Outfit',
      fontStyle: 'normal',
      fontWeight: '600',
      letterSpacing: 'normal',
      textTransform: 'none',
      fontSizeBase: '14px',
      logoUrl: `data:image/svg+xml;utf8,<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 240 60"><rect width="240" height="60" rx="8" fill="%23007CC3"/><text x="24" y="38" fill="%23FFFFFF" font-family="Arial, sans-serif" font-size="24" font-style="italic" font-weight="900">Infosys</text><text x="120" y="36" fill="%23E0F2FE" font-family="Arial, sans-serif" font-size="13" font-weight="600">ENTERPRISE</text></svg>`,
      logoFileName: 'infosys_enterprise_logo.svg',
      logoHeightPx: 36,
    },
    createdAt: '2025-05-10T09:00:00Z',
  },
];

export const INITIAL_SITES: Site[] = [
  {
    id: 'site-blr-01',
    tenantId: 'ten-tata-01',
    name: 'Bengaluru Global Technology Hub (Electronic City)',
    code: 'BLR-GTH',
    timezone: 'Asia/Kolkata',
    address: 'Plot 42, Electronic City Phase 1, Hosur Road, Bengaluru, Karnataka 560100',
    status: 'ACTIVE',
    visitorPolicy: 'Government photo ID (Aadhaar/PAN/Passport) required. Escort mandatory in Zone B and C.',
    requiresHostApproval: true,
    requiresSecurityApproval: true,
  },
  {
    id: 'site-bom-02',
    tenantId: 'ten-tata-01',
    name: 'Mumbai Corporate Tower & BFSI Data Center (BKC)',
    code: 'BOM-BKC',
    timezone: 'Asia/Kolkata',
    address: 'G-Block, Bandra Kurla Complex (BKC), Bandra East, Mumbai, Maharashtra 400051',
    status: 'ACTIVE',
    visitorPolicy: 'Strict biometric verification & digital badge required. Escort mandatory on server floors.',
    requiresHostApproval: true,
    requiresSecurityApproval: false,
  },
  {
    id: 'site-hyd-03',
    tenantId: 'ten-reliance-02',
    name: 'Hyderabad Tech Gateway (HITEC City)',
    code: 'HYD-HTC',
    timezone: 'Asia/Kolkata',
    address: 'Cyber Gateway, Phase 2, Madhapur, HITEC City, Hyderabad, Telangana 500081',
    status: 'ACTIVE',
    visitorPolicy: 'Visitor pre-registration with OTP and Government ID mandatory for badge issuance.',
    requiresHostApproval: true,
    requiresSecurityApproval: true,
  },
  {
    id: 'site-del-04',
    tenantId: 'ten-infosys-03',
    name: 'Gurugram Cyber City Campus (DLF Phase 2)',
    code: 'DEL-CYB',
    timezone: 'Asia/Kolkata',
    address: 'Building 10, DLF Cyber City, Sector 24, Gurugram, Haryana 122002',
    status: 'ACTIVE',
    visitorPolicy: 'Strict NDA & dual-level security approval before thermal badge printing.',
    requiresHostApproval: true,
    requiresSecurityApproval: true,
  },
];

export const INITIAL_ZONES: BuildingZone[] = [
  {
    id: 'zone-lobby-1',
    siteId: 'site-blr-01',
    name: 'Main Reception Atrium & Innovation Center',
    code: 'ZN-LOBBY-01',
    securityLevel: 'LOW',
    musterPoint: 'Assembly Area 1 (Central Amphitheatre Green)',
    maxCapacity: 150,
  },
  {
    id: 'zone-rnd-2',
    siteId: 'site-blr-01',
    name: 'AI & Autonomous Robotics Center of Excellence',
    code: 'ZN-AI-RND',
    securityLevel: 'HIGH',
    musterPoint: 'Assembly Area 2 (West Perimeter Lawn, Gate 3)',
    maxCapacity: 50,
  },
  {
    id: 'zone-datacenter-3',
    siteId: 'site-blr-01',
    name: 'Tier-4 Hybrid Cloud Operations & Cyber SOC',
    code: 'ZN-SOC-SEC',
    securityLevel: 'RESTRICTED',
    musterPoint: 'Assembly Area 2 (West Perimeter Lawn, Gate 3)',
    maxCapacity: 25,
  },
  {
    id: 'zone-mumbai-vault',
    siteId: 'site-bom-02',
    name: 'BFSI Core Transaction Vault & Switch',
    code: 'ZN-BKC-VAULT',
    securityLevel: 'RESTRICTED',
    musterPoint: 'Muster Point East Plinth (BKC Avenue)',
    maxCapacity: 100,
  },
];

export const INITIAL_GATES: Gate[] = [
  {
    id: 'gate-blr-main',
    siteId: 'site-blr-01',
    name: 'Main Reception Turnstiles (Gate 1 - North Atrium)',
    code: 'GT-BLR-01',
    type: 'BIDIRECTIONAL',
    operatingStatus: 'OPEN',
    assignedPrinterId: 'dev-printer-01',
    assignedTerminalId: 'dev-term-01',
  },
  {
    id: 'gate-blr-logistics',
    siteId: 'site-blr-01',
    name: 'Logistics & Freight Bay (Gate 4 - South Logistics)',
    code: 'GT-BLR-02',
    type: 'ENTRY_ONLY',
    operatingStatus: 'OPEN',
    assignedPrinterId: 'dev-printer-02',
    assignedTerminalId: 'dev-term-02',
  },
  {
    id: 'gate-blr-vip',
    siteId: 'site-blr-01',
    name: 'VIP & Executive Board Access (Gate 2 - Portico)',
    code: 'GT-BLR-03',
    type: 'EXIT_ONLY',
    operatingStatus: 'RESTRICTED',
  },
  {
    id: 'gate-bom-main',
    siteId: 'site-bom-02',
    name: 'BKC Ground Security Turnstiles (Gate Alpha)',
    code: 'GT-BOM-01',
    type: 'BIDIRECTIONAL',
    operatingStatus: 'OPEN',
  },
];

export const INITIAL_DEPARTMENTS: Department[] = [
  {
    id: 'dept-eng',
    tenantId: 'ten-tata-01',
    name: 'Hardware & Cloud Infrastructure Engineering',
    code: 'ENG',
    leadApproverId: 'usr-rajesh',
    leadApproverName: 'Dr. Rajesh Sengupta',
  },
  {
    id: 'dept-sec',
    tenantId: 'ten-tata-01',
    name: 'Corporate Physical Security & Cyber SOC Ops',
    code: 'SECOPS',
    leadApproverId: 'usr-vikram',
    leadApproverName: 'Vikramaditya Chauhan',
  },
  {
    id: 'dept-fac',
    tenantId: 'ten-tata-01',
    name: 'Facilities & Workplace Infrastructure',
    code: 'FAC',
    leadApproverId: 'usr-pooja',
    leadApproverName: 'Pooja Deshmukh',
  },
  {
    id: 'dept-exec',
    tenantId: 'ten-tata-01',
    name: 'Executive Board & Strategic Alliances',
    code: 'EXEC',
    leadApproverId: 'usr-arun',
    leadApproverName: 'Arun Mehra',
  },
];

export const INITIAL_USERS: AppUser[] = [
  {
    id: 'usr-ananya',
    tenantId: 'ten-tata-01',
    name: 'Ananya Sharma',
    loginId: 'ananya',
    email: 'ananya.sharma@platform-admin.gov.in',
    password: 'Admin#321',
    phoneNumber: '+91 98201 11001',
    role: 'PLATFORM_SUPER_ADMIN',
    departmentId: 'dept-sec',
    departmentName: 'Platform Operations',
    siteScopes: ['*'],
    gateScopes: ['*'],
    mfaEnabled: true,
    status: 'ACTIVE',
    lastLoginAt: '2026-09-20T07:14:00Z',
    notificationSettings: {
      enableSms: true,
      smsPhoneNumber: '+91 98201 11001',
      enableEmail: true,
      alertEmail: 'ananya.sharma@platform-admin.gov.in',
      enableSlack: true,
      slackWebhookUrl: 'https://hooks.slack.com/services/T00/B00/admin-alerts',
      slackChannel: '#vms-executive-alerts',
      alertOnArrival: true,
      alertOnCheckOut: true,
      alertOnPendingApproval: true,
    },
  },
  {
    id: 'usr-arun',
    tenantId: 'ten-tata-01',
    name: 'Arun Mehra',
    loginId: 'arun',
    email: 'arun.mehra@tata-enterprise.com',
    password: 'admin123',
    phoneNumber: '+91 98202 22002',
    role: 'TENANT_ADMIN',
    departmentId: 'dept-exec',
    departmentName: 'Executive Board & Strategic Alliances',
    siteScopes: ['*'],
    gateScopes: ['*'],
    mfaEnabled: true,
    status: 'ACTIVE',
    lastLoginAt: '2026-09-20T06:45:00Z',
    notificationSettings: {
      enableSms: true,
      smsPhoneNumber: '+91 98202 22002',
      enableEmail: true,
      alertEmail: 'arun.mehra@tata-enterprise.com',
      enableSlack: true,
      slackWebhookUrl: 'https://hooks.slack.com/services/T00/B00/exec-board',
      slackChannel: '#exec-boardroom-guests',
      alertOnArrival: true,
      alertOnCheckOut: false,
      alertOnPendingApproval: true,
    },
  },
  {
    id: 'usr-vikram',
    tenantId: 'ten-tata-01',
    name: 'Vikramaditya Chauhan',
    loginId: 'vikram',
    email: 'vikram.chauhan@tata-security.in',
    password: 'security123',
    phoneNumber: '+91 98203 33003',
    role: 'TENANT_SECURITY_ADMIN',
    departmentId: 'dept-sec',
    departmentName: 'Corporate Physical Security & Cyber SOC Ops',
    siteScopes: ['*'],
    gateScopes: ['*'],
    mfaEnabled: true,
    status: 'ACTIVE',
    lastLoginAt: '2026-09-20T07:30:00Z',
    notificationSettings: {
      enableSms: true,
      smsPhoneNumber: '+91 98203 33003',
      enableEmail: true,
      alertEmail: 'vikram.chauhan@tata-security.in',
      enableSlack: true,
      slackWebhookUrl: 'https://hooks.slack.com/services/T00/B00/soc-security',
      slackChannel: '#security-gate-dispatch',
      alertOnArrival: true,
      alertOnCheckOut: true,
      alertOnPendingApproval: true,
    },
  },
  {
    id: 'usr-priya',
    tenantId: 'ten-tata-01',
    name: 'Priya Nair',
    loginId: 'priya',
    email: 'priya.nair@tata-reception.in',
    password: 'reception123',
    phoneNumber: '+91 98204 44004',
    role: 'RECEPTIONIST',
    departmentId: 'dept-fac',
    departmentName: 'Facilities & Workplace Infrastructure',
    siteScopes: ['site-blr-01'],
    gateScopes: ['gate-blr-main'],
    mfaEnabled: false,
    status: 'ACTIVE',
    lastLoginAt: '2026-09-20T07:55:00Z',
    notificationSettings: {
      enableSms: false,
      smsPhoneNumber: '+91 98204 44004',
      enableEmail: true,
      alertEmail: 'priya.nair@tata-reception.in',
      enableSlack: true,
      slackWebhookUrl: 'https://hooks.slack.com/services/T00/B00/reception-desk',
      slackChannel: '#frontdesk-turnstiles',
      alertOnArrival: true,
      alertOnCheckOut: true,
      alertOnPendingApproval: false,
    },
  },
  {
    id: 'usr-suresh',
    tenantId: 'ten-tata-01',
    name: 'Subedar Suresh Patil',
    loginId: 'suresh',
    email: 'suresh.patil@securityguard.in',
    password: 'guard123',
    phoneNumber: '+91 98205 55005',
    role: 'SECURITY_GUARD',
    departmentId: 'dept-sec',
    departmentName: 'Corporate Physical Security & Cyber SOC Ops',
    siteScopes: ['site-blr-01'],
    gateScopes: ['gate-blr-main', 'gate-blr-logistics', 'gate-blr-vip'],
    mfaEnabled: false,
    status: 'ACTIVE',
    lastLoginAt: '2026-09-20T07:50:00Z',
    notificationSettings: {
      enableSms: true,
      smsPhoneNumber: '+91 98205 55005',
      enableEmail: false,
      alertEmail: 'suresh.patil@securityguard.in',
      enableSlack: false,
      slackWebhookUrl: '',
      slackChannel: '#gate-security',
      alertOnArrival: true,
      alertOnCheckOut: true,
      alertOnPendingApproval: false,
    },
  },
  {
    id: 'usr-rajesh',
    tenantId: 'ten-tata-01',
    name: 'Dr. Rajesh Sengupta',
    loginId: 'rajesh',
    email: 'rajesh.sengupta@tata-eng.in',
    password: 'host123',
    phoneNumber: '+91 98206 66006',
    role: 'HOST_EMPLOYEE',
    departmentId: 'dept-eng',
    departmentName: 'Hardware & Cloud Infrastructure Engineering',
    siteScopes: ['site-blr-01'],
    gateScopes: ['*'],
    mfaEnabled: true,
    status: 'ACTIVE',
    lastLoginAt: '2026-09-19T18:22:00Z',
    notificationSettings: {
      enableSms: true,
      smsPhoneNumber: '+91 98206 66006',
      enableEmail: true,
      alertEmail: 'rajesh.sengupta@tata-eng.in',
      enableSlack: true,
      slackWebhookUrl: 'https://hooks.slack.com/services/T00/B00/engineering-hosts',
      slackChannel: '#engineering-visitor-alerts',
      alertOnArrival: true,
      alertOnCheckOut: true,
      alertOnPendingApproval: true,
    },
  },
  {
    id: 'usr-pooja',
    tenantId: 'ten-tata-01',
    name: 'Pooja Deshmukh',
    loginId: 'pooja',
    email: 'pooja.deshmukh@tata-approvals.in',
    password: 'approver123',
    phoneNumber: '+91 98207 77007',
    role: 'DEPARTMENT_APPROVER',
    departmentId: 'dept-fac',
    departmentName: 'Facilities & Workplace Infrastructure',
    siteScopes: ['site-blr-01', 'site-bom-02'],
    gateScopes: ['*'],
    mfaEnabled: true,
    status: 'ACTIVE',
    lastLoginAt: '2026-09-20T07:10:00Z',
    notificationSettings: {
      enableSms: true,
      smsPhoneNumber: '+91 98207 77007',
      enableEmail: true,
      alertEmail: 'pooja.deshmukh@tata-approvals.in',
      enableSlack: true,
      slackWebhookUrl: 'https://hooks.slack.com/services/T00/B00/approver-channel',
      slackChannel: '#department-approvals',
      alertOnArrival: true,
      alertOnCheckOut: false,
      alertOnPendingApproval: true,
    },
  },
  {
    id: 'usr-kavita',
    tenantId: 'ten-tata-01',
    name: 'Kavita Iyer',
    loginId: 'kavita',
    email: 'kavita.iyer@audit-compliance.in',
    password: 'auditor123',
    phoneNumber: '+91 98208 88008',
    role: 'COMPLIANCE_AUDITOR',
    departmentId: 'dept-sec',
    departmentName: 'Independent Regulatory Audit',
    siteScopes: ['*'],
    gateScopes: ['*'],
    mfaEnabled: true,
    status: 'ACTIVE',
    lastLoginAt: '2026-09-20T05:12:00Z',
    notificationSettings: {
      enableSms: false,
      smsPhoneNumber: '+91 98208 88008',
      enableEmail: true,
      alertEmail: 'kavita.iyer@audit-compliance.in',
      enableSlack: false,
      slackWebhookUrl: '',
      slackChannel: '#audit-logs',
      alertOnArrival: false,
      alertOnCheckOut: false,
      alertOnPendingApproval: false,
    },
  },
];

export const INITIAL_VISITORS: VisitorProfile[] = [
  {
    id: 'vis-001',
    tenantId: 'ten-tata-01',
    fullName: 'Sneha Kulkarni',
    email: 'sneha.kulkarni@wipro-solutions.com',
    phoneNumber: '+91 98201 55420',
    company: 'Wipro Digital Systems',
    category: 'BUSINESS_GUEST',
    documentType: 'NATIONAL_ID',
    maskedDocumentNumber: '••••-••••-8819',
    consentSigned: true,
    consentSignedAt: '2026-09-20T08:00:00Z',
    ndaSigned: true,
    photoUrl: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=150&auto=format&fit=crop&q=80',
    watchlistStatus: 'CLEAN',
    totalVisits: 3,
    lastVisitAt: '2026-09-14T09:00:00Z',
    createdAt: '2026-01-10T11:00:00Z',
  },
  {
    id: 'vis-002',
    tenantId: 'ten-tata-01',
    fullName: 'Rohan Verma',
    email: 'rohan.v@larsentoubro-infra.com',
    phoneNumber: '+91 97112 43102',
    company: 'Larsen & Toubro Infra Solutions',
    category: 'CONTRACTOR',
    documentType: 'PASSPORT',
    maskedDocumentNumber: '••••-••••-4102',
    consentSigned: true,
    consentSignedAt: '2026-09-20T08:15:00Z',
    ndaSigned: true,
    photoUrl: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150&auto=format&fit=crop&q=80',
    watchlistStatus: 'CLEAN',
    totalVisits: 12,
    lastVisitAt: '2026-09-19T08:00:00Z',
    createdAt: '2025-11-04T09:30:00Z',
  },
  {
    id: 'vis-003',
    tenantId: 'ten-tata-01',
    fullName: 'Dr. Arvind Swaminathan',
    email: 'swaminathan@iisc.ac.in',
    phoneNumber: '+91 94480 19011',
    company: 'Indian Institute of Science (IISc)',
    category: 'VIP_EXECUTIVE',
    documentType: 'PASSPORT',
    maskedDocumentNumber: '••••-••••-9011',
    consentSigned: true,
    consentSignedAt: '2026-09-19T14:00:00Z',
    ndaSigned: true,
    photoUrl: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150&auto=format&fit=crop&q=80',
    watchlistStatus: 'CLEAN',
    totalVisits: 1,
    createdAt: '2026-09-15T10:00:00Z',
  },
  {
    id: 'vis-004',
    tenantId: 'ten-tata-01',
    fullName: 'Amitabh Saxena',
    email: 'a.saxena@meity.gov.in',
    phoneNumber: '+91 98102 33201',
    company: 'Ministry of Electronics & IT (MeitY)',
    category: 'REGULATORY_AUDITOR',
    documentType: 'GOVERNMENT_BADGE',
    maskedDocumentNumber: '••••-••••-3320',
    consentSigned: true,
    consentSignedAt: '2026-09-20T07:45:00Z',
    ndaSigned: false,
    watchlistStatus: 'CLEAN',
    totalVisits: 2,
    lastVisitAt: '2026-06-12T10:00:00Z',
    createdAt: '2026-06-01T08:00:00Z',
  },
  {
    id: 'vis-005',
    tenantId: 'ten-tata-01',
    fullName: 'Deepak Yadav',
    email: 'deepak.y@bluedart-express.in',
    phoneNumber: '+91 99304 88321',
    company: 'Blue Dart Express Logistics',
    category: 'DELIVERY_DISPATCH',
    documentType: 'DRIVERS_LICENSE',
    maskedDocumentNumber: '••••-••••-1192',
    consentSigned: true,
    ndaSigned: false,
    watchlistStatus: 'NEEDS_VERIFICATION',
    totalVisits: 0,
    createdAt: '2026-09-20T08:30:00Z',
  },
];

export const INITIAL_VISITS: Visit[] = [
  {
    id: 'vst-101',
    tenantId: 'ten-tata-01',
    siteId: 'site-blr-01',
    siteName: 'Bengaluru Global Technology Hub (Electronic City)',
    gateId: 'gate-blr-main',
    gateName: 'Main Reception Turnstiles (Gate 1 - North Atrium)',
    visitorId: 'vis-001',
    visitorName: 'Sneha Kulkarni',
    visitorCompany: 'Wipro Digital Systems',
    visitorCategory: 'BUSINESS_GUEST',
    hostUserId: 'usr-rajesh',
    hostName: 'Dr. Rajesh Sengupta',
    departmentId: 'dept-eng',
    departmentName: 'Hardware & Cloud Infrastructure Engineering',
    purpose: 'Quarterly Architecture Review for Semiconductor Edge Controllers',
    scheduledStart: '2026-09-20T08:30:00Z',
    scheduledEnd: '2026-09-20T17:00:00Z',
    actualCheckIn: '2026-09-20T08:42:00Z',
    state: 'CHECKED_IN',
    passToken: 'PASS-TATA-BLR-88192A',
    passTokenExpiresAt: '2026-09-20T23:59:59Z',
    badgeId: 'bdg-001',
    badgeNumber: 'TATA-BLR-0081',
    entryGateId: 'gate-blr-main',
    checkedInBy: 'usr-priya',
    assignedZone: 'zone-lobby-1',
    musterPoint: 'Assembly Area 1 (Central Amphitheatre Green)',
    isAccountedForInEmergency: true,
    approvalStatus: {
      hostApproved: true,
      hostApprovedAt: '2026-09-19T10:15:00Z',
      departmentApproved: true,
      departmentApprovedAt: '2026-09-19T11:00:00Z',
      securityApproved: true,
      securityApprovedAt: '2026-09-19T14:30:00Z',
    },
    createdAt: '2026-09-18T09:00:00Z',
  },
  {
    id: 'vst-102',
    tenantId: 'ten-tata-01',
    siteId: 'site-blr-01',
    siteName: 'Bengaluru Global Technology Hub (Electronic City)',
    gateId: 'gate-blr-logistics',
    gateName: 'Logistics & Freight Bay (Gate 4 - South Logistics)',
    visitorId: 'vis-002',
    visitorName: 'Rohan Verma',
    visitorCompany: 'Larsen & Toubro Infra Solutions',
    visitorCategory: 'CONTRACTOR',
    hostUserId: 'usr-pooja',
    hostName: 'Pooja Deshmukh',
    departmentId: 'dept-fac',
    departmentName: 'Facilities & Workplace Infrastructure',
    purpose: 'HVAC Precision Chiller Unit Overhaul & Thermal Testing',
    scheduledStart: '2026-09-20T08:00:00Z',
    scheduledEnd: '2026-09-20T16:00:00Z',
    actualCheckIn: '2026-09-20T08:14:00Z',
    state: 'CHECKED_IN',
    passToken: 'PASS-TATA-BLR-44910B',
    passTokenExpiresAt: '2026-09-20T20:00:00Z',
    badgeId: 'bdg-002',
    badgeNumber: 'TATA-CONTR-0199',
    entryGateId: 'gate-blr-logistics',
    checkedInBy: 'usr-suresh',
    assignedZone: 'zone-rnd-2',
    musterPoint: 'Assembly Area 2 (West Perimeter Lawn, Gate 3)',
    isAccountedForInEmergency: false,
    approvalStatus: {
      hostApproved: true,
      hostApprovedAt: '2026-09-18T16:00:00Z',
      securityApproved: true,
      securityApprovedAt: '2026-09-19T09:00:00Z',
    },
    createdAt: '2026-09-18T14:00:00Z',
  },
  {
    id: 'vst-103',
    tenantId: 'ten-tata-01',
    siteId: 'site-blr-01',
    siteName: 'Bengaluru Global Technology Hub (Electronic City)',
    gateId: 'gate-blr-main',
    gateName: 'Main Reception Turnstiles (Gate 1 - North Atrium)',
    visitorId: 'vis-003',
    visitorName: 'Dr. Arvind Swaminathan',
    visitorCompany: 'Indian Institute of Science (IISc)',
    visitorCategory: 'VIP_EXECUTIVE',
    hostUserId: 'usr-arun',
    hostName: 'Arun Mehra',
    departmentId: 'dept-exec',
    departmentName: 'Executive Board & Strategic Alliances',
    purpose: 'Executive Roundtable on Sovereign Quantum Computing & VIP Tour',
    scheduledStart: '2026-09-20T10:00:00Z',
    scheduledEnd: '2026-09-20T15:30:00Z',
    state: 'APPROVED',
    passToken: 'PASS-TATA-BLR-VIP901',
    passTokenExpiresAt: '2026-09-20T23:59:59Z',
    assignedZone: 'zone-lobby-1',
    musterPoint: 'Assembly Area 1 (Central Amphitheatre Green)',
    approvalStatus: {
      hostApproved: true,
      hostApprovedAt: '2026-09-19T11:00:00Z',
      securityApproved: true,
      securityApprovedAt: '2026-09-19T14:00:00Z',
    },
    createdAt: '2026-09-17T09:00:00Z',
  },
  {
    id: 'vst-104',
    tenantId: 'ten-tata-01',
    siteId: 'site-blr-01',
    siteName: 'Bengaluru Global Technology Hub (Electronic City)',
    gateId: 'gate-blr-main',
    gateName: 'Main Reception Turnstiles (Gate 1 - North Atrium)',
    visitorId: 'vis-004',
    visitorName: 'Amitabh Saxena',
    visitorCompany: 'Ministry of Electronics & IT (MeitY)',
    visitorCategory: 'REGULATORY_AUDITOR',
    hostUserId: 'usr-vikram',
    hostName: 'Vikramaditya Chauhan',
    departmentId: 'dept-sec',
    departmentName: 'Corporate Physical Security & Cyber SOC Ops',
    purpose: 'Statutory ISO 27001 & CERT-In Physical Security Audit',
    scheduledStart: '2026-09-20T11:00:00Z',
    scheduledEnd: '2026-09-20T14:00:00Z',
    state: 'PENDING_APPROVAL',
    passToken: 'PASS-TATA-BLR-AUD772',
    passTokenExpiresAt: '2026-09-20T18:00:00Z',
    assignedZone: 'zone-rnd-2',
    approvalStatus: {
      hostApproved: true,
      hostApprovedAt: '2026-09-20T08:00:00Z',
      securityApproved: false,
    },
    createdAt: '2026-09-20T07:50:00Z',
  },
  {
    id: 'vst-105',
    tenantId: 'ten-tata-01',
    siteId: 'site-blr-01',
    siteName: 'Bengaluru Global Technology Hub (Electronic City)',
    gateId: 'gate-blr-main',
    gateName: 'Main Reception Turnstiles (Gate 1 - North Atrium)',
    visitorId: 'vis-005',
    visitorName: 'Deepak Yadav',
    visitorCompany: 'Blue Dart Express Logistics',
    visitorCategory: 'DELIVERY_DISPATCH',
    hostUserId: 'usr-priya',
    hostName: 'Priya Nair',
    departmentId: 'dept-fac',
    departmentName: 'Facilities & Workplace Infrastructure',
    purpose: 'Urgent High-Priority Cryptographic HSM Hardware Delivery',
    scheduledStart: '2026-09-20T09:15:00Z',
    scheduledEnd: '2026-09-20T09:45:00Z',
    state: 'ARRIVED',
    passToken: 'PASS-TATA-BLR-DEL005',
    passTokenExpiresAt: '2026-09-20T12:00:00Z',
    assignedZone: 'zone-lobby-1',
    approvalStatus: {
      hostApproved: true,
      hostApprovedAt: '2026-09-20T08:45:00Z',
      securityApproved: true,
      securityApprovedAt: '2026-09-20T08:50:00Z',
    },
    createdAt: '2026-09-20T08:40:00Z',
  },
];

export const INITIAL_BADGE_TEMPLATES: BadgeTemplate[] = [
  {
    id: 'tmpl-standard-01',
    tenantId: 'ten-tata-01',
    name: 'Standard Tata Enterprise Visitor Pass (CR80 PVC)',
    type: 'CR80_CARD',
    widthMm: 85.6,
    heightMm: 53.98,
    showPhoto: true,
    showQrCode: true,
    showHost: true,
    showCategoryColor: true,
    headerBackground: '#123B5D',
    instructions: 'Must be visibly worn at all times above the waist. Return to reception turnstile upon checkout.',
  },
  {
    id: 'tmpl-contractor-02',
    tenantId: 'ten-tata-01',
    name: 'Contractor Industrial Safety Pass (High-Vis Adhesive)',
    type: 'ADHESIVE_LABEL',
    widthMm: 101.6,
    heightMm: 76.2,
    showPhoto: true,
    showQrCode: true,
    showHost: true,
    showCategoryColor: true,
    headerBackground: '#B45309',
    instructions: 'SAFETY HELMET & ESCORT MANDATORY IN R&D ZONES. Valid for designated date only.',
  },
  {
    id: 'tmpl-vip-03',
    tenantId: 'ten-tata-01',
    name: 'Executive VIP Direct Access Pass',
    type: 'CR80_CARD',
    widthMm: 85.6,
    heightMm: 53.98,
    showPhoto: true,
    showQrCode: true,
    showHost: true,
    showCategoryColor: true,
    headerBackground: '#0F766E',
    instructions: 'Executive Boardroom & Guest Lounge Access. Priority clearance across campus.',
  },
];

export const INITIAL_DEVICES: HardwareDevice[] = [
  {
    id: 'dev-printer-01',
    tenantId: 'ten-tata-01',
    siteId: 'site-blr-01',
    gateId: 'gate-blr-main',
    name: 'TVS-Zebra ZD421 Thermal Badge Printer (Desk 1 - North Reception)',
    identifier: 'PRN-TVS-8812',
    type: 'BADGE_PRINTER',
    model: 'Zebra ZD421 Direct Thermal 300DPI',
    ipAddress: '10.24.110.42',
    status: 'ONLINE',
    lastHeartbeat: '2026-09-20T08:52:10Z',
    firmwareVersion: 'v7.4.2-rel',
  },
  {
    id: 'dev-printer-02',
    tenantId: 'ten-tata-01',
    siteId: 'site-blr-01',
    gateId: 'gate-blr-logistics',
    name: 'TVS-Brother QL-820NWB Wireless Label Printer (Gate 4 Logistics)',
    identifier: 'PRN-BTH-4019',
    type: 'BADGE_PRINTER',
    model: 'Brother QL-820NWB Ultra-High Speed',
    ipAddress: '10.24.110.43',
    status: 'ONLINE',
    lastHeartbeat: '2026-09-20T08:51:30Z',
    firmwareVersion: 'v2.18-std',
  },
  {
    id: 'dev-term-01',
    tenantId: 'ten-tata-01',
    siteId: 'site-blr-01',
    gateId: 'gate-blr-main',
    name: 'Self-Service Visitor Kiosk Alpha (Electronic City Gate 1)',
    identifier: 'KSK-IPAD-01',
    type: 'RECEPTION_KIOSK',
    model: 'iPad Pro 12.9 Secure Enclosure',
    ipAddress: '10.24.110.15',
    status: 'ONLINE',
    lastHeartbeat: '2026-09-20T08:54:02Z',
    firmwareVersion: 'vms-kiosk-v3.2',
    batteryPercentage: 98,
  },
  {
    id: 'dev-scanner-01',
    tenantId: 'ten-tata-01',
    siteId: 'site-blr-01',
    gateId: 'gate-blr-main',
    name: 'Honeywell Genesis 7580g 2D Turnstile QR Reader (Gate 1)',
    identifier: 'SCN-HNY-102',
    type: 'QR_SCANNER',
    model: 'Honeywell Genesis 7580g Presentation',
    ipAddress: '10.24.110.22',
    status: 'ONLINE',
    lastHeartbeat: '2026-09-20T08:53:15Z',
    firmwareVersion: 'v1.12',
  },
  {
    id: 'dev-edge-01',
    tenantId: 'ten-tata-01',
    siteId: 'site-blr-01',
    gateId: 'gate-blr-main',
    name: 'Bengaluru Edge Node Gateway - Advantech IoT (Gate 1 Turnstiles)',
    identifier: 'EDG-NODE-BLR-01',
    type: 'EDGE_CONTROLLER',
    model: 'Advantech UNO-2271G Fanless Edge Box',
    ipAddress: '10.24.110.1',
    status: 'ONLINE',
    lastHeartbeat: '2026-09-20T08:54:30Z',
    firmwareVersion: 'edge-agent-v1.4.0',
  },
];

export const INITIAL_AUDIT_EVENTS: AuditEvent[] = [
  {
    id: 'aud-001',
    timestamp: '2026-09-20T08:42:15Z',
    tenantId: 'ten-tata-01',
    siteId: 'site-blr-01',
    gateId: 'gate-blr-main',
    actorId: 'usr-priya',
    actorName: 'Priya Nair',
    actorRole: 'RECEPTIONIST',
    eventType: 'VISIT_CHECKED_IN',
    action: 'CHECK_IN',
    entityType: 'VISIT',
    entityId: 'vst-101',
    previousState: 'ARRIVED',
    newState: 'CHECKED_IN',
    details: 'Visitor Sneha Kulkarni checked in at Gate 1 turnstiles. Badge TATA-BLR-0081 dispatched.',
    correlationId: 'corr-88219-chk-01',
    ipAddress: '10.24.110.15',
    status: 'SUCCESS',
  },
  {
    id: 'aud-002',
    timestamp: '2026-09-20T08:42:10Z',
    tenantId: 'ten-tata-01',
    siteId: 'site-blr-01',
    gateId: 'gate-blr-main',
    actorId: 'usr-priya',
    actorName: 'Priya Nair',
    actorRole: 'RECEPTIONIST',
    eventType: 'BADGE_PRINT_DISPATCH',
    action: 'PRINT',
    entityType: 'BADGE',
    entityId: 'bdg-001',
    details: 'Triggered thermal print job to TVS-Zebra ZD421 (PRN-TVS-8812) with idempotency key idmp-vst-101.',
    correlationId: 'corr-88219-chk-01',
    ipAddress: '10.24.110.15',
    status: 'SUCCESS',
  },
  {
    id: 'aud-003',
    timestamp: '2026-09-20T08:14:22Z',
    tenantId: 'ten-tata-01',
    siteId: 'site-blr-01',
    gateId: 'gate-blr-logistics',
    actorId: 'usr-suresh',
    actorName: 'Subedar Suresh Patil',
    actorRole: 'SECURITY_GUARD',
    eventType: 'VISIT_CHECKED_IN',
    action: 'CHECK_IN',
    entityType: 'VISIT',
    entityId: 'vst-102',
    previousState: 'APPROVED',
    newState: 'CHECKED_IN',
    details: 'Contractor Rohan Verma checked in at Logistics Gate 4 with PPE and safety verification.',
    correlationId: 'corr-44109-chk-02',
    ipAddress: '10.24.110.43',
    status: 'SUCCESS',
  },
  {
    id: 'aud-004',
    timestamp: '2026-09-20T07:52:00Z',
    tenantId: 'ten-tata-01',
    siteId: 'site-blr-01',
    actorId: 'usr-vikram',
    actorName: 'Vikramaditya Chauhan',
    actorRole: 'TENANT_SECURITY_ADMIN',
    eventType: 'APPROVAL_SECURITY_GRANTED',
    action: 'APPROVE',
    entityType: 'VISIT',
    entityId: 'vst-105',
    previousState: 'PENDING_APPROVAL',
    newState: 'APPROVED',
    details: 'Security pre-clearance granted for express HSM hardware courier.',
    correlationId: 'corr-10928-apr-01',
    ipAddress: '10.24.110.5',
    status: 'SUCCESS',
  },
  {
    id: 'aud-005',
    timestamp: '2026-09-20T07:15:30Z',
    tenantId: 'ten-tata-01',
    actorId: 'usr-arun',
    actorName: 'Arun Mehra',
    actorRole: 'TENANT_ADMIN',
    eventType: 'CONFIG_RETENTION_POLICY_UPDATE',
    action: 'UPDATE',
    entityType: 'TENANT',
    entityId: 'ten-tata-01',
    details: 'Updated visitor data auto-purging retention window to 365 days in compliance with ISO 27001 & DPDP Act.',
    correlationId: 'corr-00918-cfg-01',
    ipAddress: '10.24.110.2',
    status: 'SUCCESS',
  },
];

export const INITIAL_EDGE_SYNC_EVENTS: EdgeSyncEvent[] = [
  {
    id: 'edg-ev-01',
    eventGuid: 'edg-guid-99120-a',
    tenantId: 'ten-tata-01',
    siteId: 'site-blr-01',
    gateId: 'gate-blr-logistics',
    eventType: 'OFFLINE_CHECK_IN',
    payload: {
      visitId: 'vst-102',
      badgeNumber: 'TATA-CONTR-0199',
      timestampUtc: '2026-09-20T08:14:22Z',
      guardId: 'usr-suresh',
      terminalOfflineDurationSeconds: 120,
    },
    capturedAtUtc: '2026-09-20T08:14:22Z',
    syncedAtUtc: '2026-09-20T08:16:30Z',
    status: 'SYNCED',
    hash: 'sha256:8f4c2e1a90b84c8e...',
  },
];

export const INITIAL_UAT_CASES: UATTestCase[] = [
  {
    id: 1,
    code: 'UAT-OIDC-001',
    name: 'Successful OIDC Login & Token Claims Mapping',
    category: 'OIDC',
    preconditions: 'OIDC provider metadata configured; active user account exists in enterprise directory.',
    testSteps: [
      'Navigate to Login page',
      'Select Enterprise OIDC Single Sign-On',
      'Authorize mock OIDC callback with valid RS256 token',
      'Verify session profile, tenant code, and user roles populated correctly',
    ],
    expectedResult: 'User authenticated with valid bearer session; claims mapped to tenant role & site scope.',
    status: 'UNTESTED',
  },
  {
    id: 2,
    code: 'UAT-OIDC-002',
    name: 'Invalid or Expired Token Handling',
    category: 'OIDC',
    preconditions: 'Expired JWT token presented in Authorization header.',
    testSteps: [
      'Inject expired session timestamp into Authorization header',
      'Attempt protected GET /api/v1/visits API call',
      'Verify 401 Unauthorized status returned with code TOKEN_EXPIRED',
    ],
    expectedResult: 'API rejects request with 401 and code TOKEN_EXPIRED; redirects user to re-authenticate.',
    status: 'UNTESTED',
  },
  {
    id: 3,
    code: 'UAT-ISO-003',
    name: 'Unauthorized Tenant Cross-Access Prevention',
    category: 'ACCESS_CONTROL',
    preconditions: 'User authenticated under Tenant TATA (ten-tata-01).',
    testSteps: [
      'User sends request querying /api/v1/tenants/ten-reliance-02 data',
      'Verify authorization middleware blocks query with 403 Forbidden',
      'Verify audit log captures security alert with actor and correlation ID',
    ],
    expectedResult: 'Access denied; zero data leakage across tenant databases.',
    status: 'UNTESTED',
  },
  {
    id: 4,
    code: 'UAT-SCP-004',
    name: 'Cross-Site Access Denial Enforcement',
    category: 'ACCESS_CONTROL',
    preconditions: 'User restricted to Bengaluru Global Technology Hub (site-blr-01).',
    testSteps: [
      'Receptionist attempts to check in visitor assigned to Mumbai Corporate Tower (site-bom-02)',
      'System evaluates siteScope against target visit siteId',
      'System rejects action with error CROSS_SITE_ACCESS_DENIED',
    ],
    expectedResult: 'Action blocked; users can only operate on visitors inside authorized site scope.',
    status: 'UNTESTED',
  },
  {
    id: 5,
    code: 'UAT-SCP-005',
    name: 'Cross-Gate Access Denial Enforcement',
    category: 'ACCESS_CONTROL',
    preconditions: 'Guard restricted to Logistics Gate 4 (gate-blr-logistics).',
    testSteps: [
      'Guard attempts check-in action through West VIP Gate 2 terminal',
      'System rejects transaction with GATE_SCOPE_MISMATCH',
    ],
    expectedResult: 'Access denied with validation message requiring designated gate assignment.',
    status: 'UNTESTED',
  },
  {
    id: 6,
    code: 'UAT-PRV-006',
    name: 'Tenant Database Provisioning Success',
    category: 'PROVISIONING',
    preconditions: 'Platform Super Admin initiating new tenant onboarding.',
    testSteps: [
      'Submit new tenant creation request with unique code and tier',
      'Execute automated database schema provisioning & migration scripts',
      'Verify tenant database reference and initial seed tables created',
    ],
    expectedResult: 'New isolated tenant database provisioned idempotently with status ACTIVE.',
    status: 'UNTESTED',
  },
  {
    id: 7,
    code: 'UAT-PRV-007',
    name: 'Tenant Provisioning Retry & Idempotency',
    category: 'PROVISIONING',
    preconditions: 'Simulate transient network timeout during tenant provisioning step.',
    testSteps: [
      'Resubmit identical tenant provisioning payload with identical idempotencyKey',
      'Verify system does not create duplicate database or duplicate tenant records',
    ],
    expectedResult: 'System returns existing provisioning state without duplicating resources.',
    status: 'UNTESTED',
  },
  {
    id: 8,
    code: 'UAT-MST-008',
    name: 'Duplicate Site / Gate Code Validation',
    category: 'ACCESS_CONTROL',
    preconditions: 'Active site BLR-GTH already exists in tenant.',
    testSteps: [
      'Attempt to create a new site with duplicate code BLR-GTH',
      'Verify schema uniqueness constraint triggers meaningful validation error',
    ],
    expectedResult: 'Rejection with 409 Conflict: Site code must be unique per tenant.',
    status: 'UNTESTED',
  },
  {
    id: 9,
    code: 'UAT-VIS-009',
    name: 'Visitor Master Profile Registration & Sensitive Masking',
    category: 'VISIT_LIFECYCLE',
    preconditions: 'Walk-in or pre-registered guest submits national ID / document.',
    testSteps: [
      'Register visitor profile with document number',
      'Verify document number is masked in all API responses and list views (••••-••••-XXXX)',
      'Verify audit trail logs creation without plaintext ID',
    ],
    expectedResult: 'Profile created; PII masked according to Zero-Trust privacy rules.',
    status: 'UNTESTED',
  },
  {
    id: 10,
    code: 'UAT-INV-010',
    name: 'Secure Invitation Creation with Cryptographic QR Token',
    category: 'VISIT_LIFECYCLE',
    preconditions: 'Host employee creating guest invitation.',
    testSteps: [
      'Host enters guest details, purpose, scheduled time window, and zone',
      'Generate secure time-limited, unguessable pass token',
      'Verify pass token expiration and digital QR payload structure',
    ],
    expectedResult: 'Invitation generated in INVITED state; digital QR pass ready for check-in.',
    status: 'UNTESTED',
  },
  {
    id: 11,
    code: 'UAT-APR-011',
    name: 'Multi-Level Approval Workflow (Host & Security)',
    category: 'VISIT_LIFECYCLE',
    preconditions: 'Visit requires dual approval (requiresHostApproval & requiresSecurityApproval).',
    testSteps: [
      'Host approves visit',
      'Verify visit remains in PENDING_APPROVAL until Security Admin approves',
      'Security Admin issues approval; verify visit state transitions to APPROVED',
    ],
    expectedResult: 'Visit transitions to APPROVED only when all mandatory approval levels are satisfied.',
    status: 'UNTESTED',
  },
  {
    id: 12,
    code: 'UAT-CHK-012',
    name: 'Check-In Blocked Without Approval',
    category: 'VISIT_LIFECYCLE',
    preconditions: 'Visit vst-104 is currently in PENDING_APPROVAL.',
    testSteps: [
      'Receptionist attempts check-in action on unapproved visit',
      'System evaluates visit state machine guard condition',
      'System rejects transaction with VISIT_NOT_APPROVED',
    ],
    expectedResult: 'Check-in blocked; state remains un-altered and warning returned.',
    status: 'UNTESTED',
  },
  {
    id: 13,
    code: 'UAT-CHK-013',
    name: 'Check-In Blocked for Expired Invitation',
    category: 'VISIT_LIFECYCLE',
    preconditions: 'Invitation passToken expired past scheduled window.',
    testSteps: [
      'Scan pass token past scheduled end timestamp',
      'Verify system checks UTC expiration timestamp against current server time',
      'Reject check-in with INVITATION_EXPIRED',
    ],
    expectedResult: 'Check-in denied with INVITATION_EXPIRED code; requires host re-issuance.',
    status: 'UNTESTED',
  },
  {
    id: 14,
    code: 'UAT-CHK-014',
    name: 'Check-Out Transaction & Live Currently-Inside Reporting',
    category: 'VISIT_LIFECYCLE',
    preconditions: 'Visitor Sneha Kulkarni (vst-101) is currently CHECKED_IN.',
    testSteps: [
      'Execute check-out action at exit gate',
      'Verify actualCheckOut timestamp recorded in UTC',
      'Verify visit state changes to CHECKED_OUT',
      'Verify live Currently-Inside dashboard counter decrements immediately',
    ],
    expectedResult: 'Check-out completed; on-premises visitor count updated in real time.',
    status: 'UNTESTED',
  },
  {
    id: 15,
    code: 'UAT-BDG-015',
    name: 'Badge Print Idempotency & Duplicate Prevention',
    category: 'BADGE_PRINT',
    preconditions: 'Print job dispatched with idempotency key idmp-vst-101.',
    testSteps: [
      'Submit second print request with identical idempotencyKey',
      'Verify system identifies existing completed print job and prevents double printing',
    ],
    expectedResult: 'Duplicate print avoided; existing print job record returned.',
    status: 'UNTESTED',
  },
  {
    id: 16,
    code: 'UAT-BDG-016',
    name: 'Printer Failure Handling & Authorized Reprint Workflow',
    category: 'BADGE_PRINT',
    preconditions: 'Simulate paper jam or offline status on thermal printer.',
    testSteps: [
      'Printer job transitions to FAILED',
      'Operator selects reprint with mandatory reason: "Damaged thermal label"',
      'System creates audited reprint job with isReprint: true',
    ],
    expectedResult: 'Reprint authorized with mandatory audit reason; printer queue updated.',
    status: 'UNTESTED',
  },
  {
    id: 17,
    code: 'UAT-AUD-017',
    name: 'Immutable Audit Event Generation for Sensitive Actions',
    category: 'AUDIT_PRIVACY',
    preconditions: 'Security action executed (check-in, override, or policy change).',
    testSteps: [
      'Perform security override on visitor clearance',
      'Verify audit record created with actorId, role, timestamp, entityId, and correlationId',
      'Verify audit records cannot be edited or deleted through UI or API',
    ],
    expectedResult: 'Tamper-evident audit event recorded with complete forensic metadata.',
    status: 'UNTESTED',
  },
  {
    id: 18,
    code: 'UAT-NTF-018',
    name: 'Transactional Outbox & Notification Dispatch',
    category: 'AUDIT_PRIVACY',
    preconditions: 'Visitor check-in event triggers host arrival notification.',
    testSteps: [
      'Create outbox event in same database transaction as check-in',
      'Outbox worker polls and delivers simulated Email / WhatsApp alert to host',
      'Verify outbox delivery status updated to DELIVERED',
    ],
    expectedResult: 'Host notified reliably via transactional outbox pattern.',
    status: 'UNTESTED',
  },
  {
    id: 19,
    code: 'UAT-EDG-019',
    name: 'Edge Offline Event Capture in Encrypted Local Queue',
    category: 'EDGE_SYNC',
    preconditions: 'Gate terminal network connectivity simulated as OFFLINE.',
    testSteps: [
      'Simulate network disconnection on Gate 1 terminal',
      'Perform visitor check-in in offline mode',
      'Verify event is captured in local encrypted queue with status PENDING_UPLOAD',
    ],
    expectedResult: 'Event stored locally with client GUID and source timestamp; UI shows Offline indicator.',
    status: 'UNTESTED',
  },
  {
    id: 20,
    code: 'UAT-EDG-020',
    name: 'Edge Synchronization & Conflict Resolution on Reconnection',
    category: 'EDGE_SYNC',
    preconditions: 'Network restored on gate terminal with 1 pending offline event.',
    testSteps: [
      'Restore network connection',
      'Trigger edge sync worker',
      'Upload buffered events to central tenant database',
      'Verify event reconciled, timestamp preserved, and status marked SYNCED',
    ],
    expectedResult: 'All offline events synchronized idempotently with clock-skew verification.',
    status: 'UNTESTED',
  },
  {
    id: 21,
    code: 'UAT-RET-021',
    name: 'Data Retention & Automatic PII Purge Enforcement',
    category: 'AUDIT_PRIVACY',
    preconditions: 'Tenant configured with 365-day retention policy.',
    testSteps: [
      'Execute automated retention compliance routine',
      'Identify records older than policy threshold',
      'Anonymize visitor PII while retaining anonymized aggregate metrics for compliance',
    ],
    expectedResult: 'Visitor PII purged according to DPDP / GDPR right to erasure rules.',
    status: 'UNTESTED',
  },
  {
    id: 22,
    code: 'UAT-MSK-022',
    name: 'Sensitive Personal Data Masking in UI & Logs',
    category: 'AUDIT_PRIVACY',
    preconditions: 'Visitor directory and search screens accessed by general users.',
    testSteps: [
      'Inspect HTML DOM and network JSON responses for visitor government ID and phone',
      'Verify characters are masked with asterisks/bullets except last 4 digits',
    ],
    expectedResult: 'Sensitive PII strictly masked in presentation layer and console logs.',
    status: 'UNTESTED',
  },
  {
    id: 23,
    code: 'UAT-EXP-023',
    name: 'Audit Trail Export Authorization & Integrity Check',
    category: 'AUDIT_PRIVACY',
    preconditions: 'User role COMPLIANCE_AUDITOR accessing Audit Explorer.',
    testSteps: [
      'Request CSV / JSON audit export',
      'Verify authorization middleware checks user role',
      'Generate export file with SHA-256 integrity checksum',
    ],
    expectedResult: 'Audit log exported securely with cryptographic checksum.',
    status: 'UNTESTED',
  },
  {
    id: 24,
    code: 'UAT-BCK-024',
    name: 'Database Backup & Point-In-Time Restore Verification',
    category: 'PROVISIONING',
    preconditions: 'Tenant database automated snapshot available.',
    testSteps: [
      'Trigger tenant database backup snapshot',
      'Simulate test restore to isolated staging schema',
      'Validate row count and foreign key referential integrity',
    ],
    expectedResult: 'Backup verified with zero data corruption and valid checksum.',
    status: 'UNTESTED',
  },
  {
    id: 25,
    code: 'UAT-PRV-025',
    name: 'Privileged Security Action Real-Time Monitoring & Alerting',
    category: 'AUDIT_PRIVACY',
    preconditions: 'Super Admin modifies emergency lockdown state or security policy.',
    testSteps: [
      'Trigger Emergency Lockdown on Site Gate 1',
      'Verify high-severity audit event generated instantly',
      'Verify SecOps banner notification displayed across active terminals',
    ],
    expectedResult: 'Immediate notification and immutable audit record for privileged security changes.',
    status: 'UNTESTED',
  },
];
